
export const FETCH_ALL_NODES = 'FETCH_ALL_NODES'
export const FETCH_NODE_INFO = 'FETCH_ONE_NODE'
export const FETCH_LATEST_TOPICS = 'FETCH_LATEST_TOPICS'
export const FETCH_HOT_TOPICS = 'FETCH_HOT_TOPICS'
export const FETCH_TOPIC_INFO = 'FETCH_ONE_TOPIC'
export const FETCH_TOPICS = 'FETCH_TOPICS'
export const FETCH_TOPIC_REPLIES = 'FETCH_TOPIC_REPLIES'
export const FETCH_MEMBER_INFO = 'FETCH_MEMBER_INFO'
